### ISSUE TITLE
training ends after some time

### ISSUE THREAD

**Issue by nikhilbyte** [bayer-science-for-a-better-life/contrastive-reconstruction#1]
I'm trying to train the model on an image directory.
Using the following parameters:

python train.py \
-o lars -lr 0.075 --lr-scaling sqrt -t 0.5 -wd 1e-4 \
--color-jitter-strength=1.0 --use-blur \
-e 1000 -bs 1 \
-m unet \
--lambda-rec=100.0 --lambda-con=1.0 \
--encoder-reduction ga_attention \
--aug-impl conrec \
--logdir /content \
--dataset image-folder \
--data-path /content/data \
--no-test-data \
--linear-type none 

which stops after few iteration with the following indication:

 2/97554 [..............................] - ETA: 3:35:03 - loss: 13.4387 - reconst_output_loss: 0.1344 - con_output_loss: 0.0000e+00 - reconst_output_mse: 0.1344 - reconst_output_mae: 0.2977 - con_output_contrastive_acc: 1.0000 - con_output_contrastive_entropy: 0.0000e+00WARNING:tensorflow:Callbacks method `on_train_batch_end` is slow compared to the batch time (batch time: 0.0361s vs `on_train_batch_end` time: 0.2279s). Check your callbacks.
WARNING:tensorflow:Callbacks method `on_train_batch_end` is slow compared to the batch time (batch time: 0.0361s vs `on_train_batch_end` time: 0.2279s). Check your callbacks.
 2126/97554 [..............................] - ETA: 2:00:26 - loss: 4.2061 - reconst_output_loss: 0.0421 - con_output_loss: 0.0000e+00 - reconst_output_mse: 0.0421 - reconst_output_mae: 0.1484 - con_output_contrastive_acc: 1.0000 - con_output_contrastive_entropy: 0.0000e+00^C

**Comment by jonasd4** [comment]
The training probably crashed due to the fact that caching the dataset was enabled by default (for performance reasons in case of small datasets). Training with a lot of images brings the cache out of memory. I disabled caching by default now with the latest commit. Furthermore, training with a batch size of 1 does not make any sense because the images in a batch are "contrasted" with the orther images in the batch. As the batch size is 1 in your case, the contrastive accuracy is always 1.0 and the contrastive loss has no effect for learning representations. Therefore, you should use at least a batch size of 8 for training.

**Comment by jonasd4** [comment]
In your case of training with 100k images, you could also use `--steps-per-epoch` argument to control the length of an epoch and therefore also the logging and model saving intervals (The model is saved after every epoch).

**Comment by nikhilbyte** [comment]
Thanks for the quick reply. 
It's working now
